<!DOCTYPE html>
<html>
    <head>
        <title>Spring Security Example </title>
    </head>
    <body>

        <form action="/login" method="post">
            <div><label> User Name : <input type="text" name="name"/> </label></div>
            <div><label> Password: <input type="email" name="email"/> </label></div>
            <div><label> User Name : <input type="text" name="phone"/> </label></div>
            <div><label> User Name : <input type="password" name="password"/> </label></div>
            <div><input type="submit" value="Sign In"/></div>
        </form>
    </body>
</html>